### ISSUE TITLE
Support other external Ids

### ISSUE THREAD

**Issue by frenos** [yakupadakli/python-tvmaze#1]
Currently only 'imdb' subkey of externals gets parsed.
Can we get the other subkeys for 'tvrage' and 'tvdb' also in the same list?

Example:
Call to api for [Game of Thrones](http://api.tvmaze.com/search/shows?q=Game%20of%20Thrones) gives

externals |  
-- | --
tvrage | 24493
thetvdb | 121361
imdb | "tt0944947"

` tvmazeAPI.show.get(82).externals`
gives only
`<External: IMDB: 'tt0944947' >`

**Comment by yakupadakli** [comment]
https://github.com/yakupadakli/python-tvmaze/pull/2

**Comment by yakupadakli** [comment]
Done
